### ISSUE TITLE
UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.

### ISSUE THREAD

**Issue by balarsen** [drsteve/PyForecastTools#11]
Steve, 

minor warning that is likely not important but thought I should put it here. 

numpy=1.18.3

```

verify.metrics.medSymAccuracy(fitted_model(x), data)

/Users/balarsen/miniconda3/envs/python3/lib/python3.7/site-packages/numpy/core/fromnumeric.py:746: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)
```

**Comment by drsteve** [comment]
Thanks @balarsen 
That warning seems to be coming up wherever the median of a masked array is being taken. If nothing is masked, no worries. Ignoring the mask is potentially bad when you have NaNs (or other masked-out values) as the median won't be what you expect. Anyway, I've made sure that I'm compressing all the masked input arrays for finding the medians.

Commit 1a877ac fixes this and adds a test to throw an exception if the warning shows up in the Sn estimator (which has medians all over the place).
