### ISSUE TITLE
Add auto-generated installation files to .gitignore

### ISSUE THREAD

**Issue by aburrell** [drsteve/PyForecastTools#5]
Installation produces 5 files: dependency_links.txt, PKG-INFO, requires.txt, SOURCES.txt, and top_level.txt.  While I'm not sure why all of these files are needed (especially top_level.txt), I think they should be added to .gitignore.

**Comment by drsteve** [comment]
Thanks. I don't see any of those files, but I'll add a .gitignore and make sure they're on it.

**Comment by drsteve** [comment]
Resolved by 96806bc

**Comment by aburrell** [comment]
There was something very weird going on when I was installing.  No idea how, but these are supposed to exist in the .egg directory.
